config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'contact', to: 'pages#contact'
  post 'contact_us', to: 'pages#contact_us'
  get 'about', to: 'pages#about'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  root to: 'pages#home'
end

app/views/pages/_contact_form.html.erb
<div class="contact-form">
  <h4>Drop us a line</h4>
  <p class="email-note" data-success="Thank you" data-error="We're sorry, there were some errors"></p>
  <%= form_for :contact_us_form, url: contact_us_path, method: :post, html: { remote: true, class: 'contact-us-form' } do |f| %>
  <%= f.text_field :author_name, label: false, placeholder: 'Your name... *', class: 'form-control' %>
  <span class="email-error-placeholder author_name_errors"></span>
  <%= f.text_field :author_phone, label: false, placeholder: 'Your phone...', class: 'form-control' %>
  <span class="email-error-placeholder author_phone_errors"></span>
  <%= f.email_field :author_email, label: false, placeholder: 'Your email... *', class: 'form-control' %>
  <span class="email-error-placeholder author_email_errors"></span>
  <%= f.text_area :message, label: false, placeholder: 'Your message *', class: 'form-control' %>
  <span class="email-error-placeholder message_errors"></span>
  <%= f.submit 'Send message', class: 'btn btn-primary form-trigger' %>
  <% end %>
</div>

app/views/pages/about.html.erb
<div class="app-card-container about">
  <div class="card">
    <h1>About Us</h1>

      <hr>

      <div class="row">
        <div class="col-md-4">
          <%= image_tag "profile.jpg", width: 250, altl: "profile image" , class: "profile-img"%>
        </div>

        <div class="col-md-8">
          <p>Here is a quick tip of peak performers that you can use to improve your daily performance and achieve yourInspector goals faster.

          The fact is successful people take personal inventory on a regular basis. It’s just like any other metric you look at in your business.</p>

          <p>Remember,  you cannot measure what you don’t track.

          If you were in sales your metrics would be things like the number appointments versus the number of closes you made in a day, week and month.
          </p>
        </div>
</div>

app/views/pages/contact.html.erb
<div class="app-card-container">
  <div class="card contact">
    <h1>Do you have a project that you would like to discuss?</h1>

    <hr>
    <div class="row">
      <div class="col-md-6">
        <h3>Office</h3>

        <p>7150 E Camelback Rd, Suite 444, Scottsdale, AZ 85251</p>

         <h3>Phone</h3>

        <p><%= number_to_phone "0877558618" %></p>

      </div>

    <div class="col-sm-6">
      <%= render 'contact_form' %>
    </div>
  </div>
 </div>
</div>

app/views/pages/home.html.erb
<div class=" special-card inner cover">
   <h1 class="cover-heading">Welcome</h1>
    <p class="lead">We are Ireland's Leading Provider of Marble and Concrete Floor Polishing, Restoration and Repair Services, With Over 20 Years Experience and Hundreds of Completed Projects..  </p>
    <p class="lead">
      <%= link_to "About Us", about_path, class: "btn btn-lg btn-secondary" %>
    </p>
</div>